apiVersion: apps/v1
kind: Deployment

metadata:
  name: specai-backend
  namespace: codecatalyst

spec:
  replicas: 1

  selector:
    matchLabels:
      app: specai-backend

  template:
    metadata:
      labels:
        app: specai-backend

    spec:
      initContainers:
        - name: prisma-migrate
          image: beetle1110/specai-backend:v7
          imagePullPolicy: Always
          command: ["sh", "-c"]
          args:
            - "npx prisma migrate deploy"
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: specai-backend-secrets
                  key: DATABASE_URL

      containers:
        - name: specai-backend
          image: beetle1110/specai-backend:v7

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: NODE_ENV
              value: "production"

            - name: PORT
              value: "5000"

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: specai-backend-secrets
                  key: DATABASE_URL

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: specai-backend-secrets
                  key: JWT_SECRET

            - name: USE_LOCAL_MODEL
              value: "true"

            - name: OLLAMA_BASE_URL
              value: "https://3d58d523d3746d.lhr.life"

            - name: OLLAMA_LLM_MODEL
              value: "gemma3:latest"

            - name: OLLAMA_EMBEDDING_MODEL
              value: "nomic-embed-text:latest"
            
            - name: PUBLIC_BASE_URL
              value: "https://codecatalyst.hackathon.sev-2.com"