apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: specai-ingress
  namespace: codecatalyst

spec:
  ingressClassName: nginx

  rules:
    - host: codecatalyst.hackathon.sev-2.com

      http:
        paths:

          # Frontend
          - path: /
            pathType: Prefix

            backend:
              service:
                name: specai-frontend-service

                port:
                  number: 80

          # Backend
          - path: /api
            pathType: Prefix

            backend:
              service:
                name: specai-backend-service

                port:
                  number: 5000